#!/usr/bin/env python3
"""Beam-search a keyboard input sequence that beats a level (plan 12 Phase 3, "game-beating").

Framed as QA infrastructure rather than a party trick: every solved level yields a scripted
input file that can be replayed through both the Rust build and the C oracle via
`scripts/live_surface_diff.sh`, turning it into permanent differential coverage. Search finds
the input; the existing harness proves the two implementations agree on it.

Design (deliberately the dumb version first)
--------------------------------------------
Candidate evaluation shells out to the real binary with a generated `POPTRACE_INPUT` script
and reads the resulting state trace. That is a whole process per candidate -- slow -- but it
needs *zero* engine changes and is correct by construction, because it drives exactly the
code path a human keyboard drives. The faster design (in-memory state snapshots via
quick_process, stepping the game in-process) is a real option later; it is not needed to find
out whether search works at all, and building it first would have meant debugging engine
surgery and a search algorithm at the same time.

Search is a beam over *input prefixes*: keep the best K prefixes, extend each by every
candidate action for one segment, evaluate, keep the best K again. Scoring prefers, in order:
reaching a later level, then getting deeper into the room graph, then surviving.

Usage:
    python3 scripts/beat_level.py --level 1 [--beam 8] [--generations 12] [--out solved.txt]
"""

import argparse
import os
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from compare_traces import read_header, read_frame  # noqa: E402

# One "segment" of input: a key held for a number of ticks. Chosen to match how a human
# actually plays -- holding right for a while, then jumping -- rather than per-tick toggling,
# which would blow up the branching factor for no gain.
SEGMENT_TICKS = 18

# The moves worth trying. Shift is the pick-up/strike/careful-step modifier; up is jump/climb.
ACTIONS = [
    ("right", []),
    ("left", []),
    ("up", []),
    ("down", []),
    ("right", ["up"]),   # running jump right
    ("left", ["up"]),    # running jump left
    ("right", ["shift"]),
    ("nop", []),
]


def build_script(prefix, tick_offset=0):
    """Render a list of (key, modifiers) segments into POPTRACE_INPUT text."""
    lines = [
        "# Generated by scripts/beat_level.py -- do not hand-edit.",
        "# Each segment holds one key (plus modifiers) for SEGMENT_TICKS ticks.",
    ]
    tick = tick_offset
    for key, mods in prefix:
        if key != "nop":
            for m in mods:
                lines.append(f"{tick} {m} down")
            lines.append(f"{tick} {key} down")
            end = tick + SEGMENT_TICKS - 2
            lines.append(f"{end} {key} up")
            for m in mods:
                lines.append(f"{end} {m} up")
        tick += SEGMENT_TICKS
    return "\n".join(lines) + "\n", tick


def field_map(fields):
    return {name: (offset, size) for name, offset, size in fields}


def read_u(blob, offset, size):
    raw = blob[offset:offset + size]
    return int.from_bytes(raw, "little", signed=False)


def evaluate(binary, level, prefix, seed, extra_ticks=60):
    """Run one candidate and return (score, reached_level, detail)."""
    script_text, end_tick = build_script(prefix)
    total_ticks = end_tick + extra_ticks

    with tempfile.TemporaryDirectory() as td:
        script_path = Path(td) / "input.txt"
        trace_path = Path(td) / "out.trace"
        script_path.write_text(script_text)

        env = dict(os.environ)
        env.update({
            "SDL_AUDIODRIVER": "dummy",
            # Without this the game paces itself to the frame timer at ~12 ticks/sec and a
            # single candidate takes tens of seconds, which puts any search out of reach.
            # Verified byte-identical to a real-time run in both builds.
            "POPTRACE_NOWAIT": "1",
            "POPTRACE_INPUT": str(script_path),
            "POPTRACE_OUT": str(trace_path),
            "POPTRACE_TICKS": str(total_ticks),
        })
        try:
            subprocess.run(
                [str(binary), f"seed={seed}", "headless", "megahit", str(level)],
                env=env, cwd=binary.parent,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                timeout=120,
            )
        except subprocess.TimeoutExpired:
            return (-1e9, level, "timeout")

        if not trace_path.exists() or trace_path.stat().st_size == 0:
            return (-1e9, level, "no trace")
        return score_trace(trace_path, level)


def score_trace(trace_path, start_level):
    """Score a run. Higher is better.

    Ordering of concerns, most to least important:
      * finishing the level (current_level advanced) dwarfs everything else
      * otherwise, visiting more distinct rooms means real progress through the level
      * staying alive matters, but only as a tiebreak -- a corpse that got far is still a
        more useful prefix than a coward standing at the start
    """
    rooms_seen = set()
    max_level = start_level
    last_hp = 0
    ticks = 0

    with open(trace_path, "rb") as f:
        fields, frame_size = read_header(f)
        fm = field_map(fields)
        lvl_off, lvl_size = fm["current_level"]
        room_off, room_size = fm["curr_room"]
        hp_off, hp_size = fm["hitp_curr"]
        while True:
            tick, blob = read_frame(f, frame_size)
            if blob is None:
                break
            ticks += 1
            max_level = max(max_level, read_u(blob, lvl_off, lvl_size))
            rooms_seen.add(read_u(blob, room_off, room_size))
            last_hp = read_u(blob, hp_off, hp_size)

    score = 0.0
    score += 1e6 * (max_level - start_level)
    score += 1000.0 * len(rooms_seen)
    score += 10.0 * last_hp
    score += 0.01 * ticks
    detail = f"level={max_level} rooms={len(rooms_seen)} hp={last_hp} ticks={ticks}"
    return (score, max_level, detail)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--level", type=int, default=1)
    ap.add_argument("--beam", type=int, default=6, help="prefixes kept per generation")
    ap.add_argument("--generations", type=int, default=10)
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--binary", default=str(ROOT / "target" / "debug" / "prince"))
    ap.add_argument("--out", default=None, help="write the winning script here")
    args = ap.parse_args()

    binary = Path(args.binary)
    if not binary.is_file():
        sys.exit(f"binary not found: {binary} (run: cargo build)")

    beam = [[]]
    best_overall = (-1e9, None, "")

    for gen in range(args.generations):
        scored = []
        for prefix in beam:
            for key, mods in ACTIONS:
                cand = prefix + [(key, mods)]
                score, lvl, detail = evaluate(binary, args.level, cand, args.seed)
                scored.append((score, cand, detail, lvl))
        scored.sort(key=lambda t: t[0], reverse=True)

        beam = [c for _, c, _, _ in scored[:args.beam]]
        top_score, top_cand, top_detail, top_level = scored[0]
        if top_score > best_overall[0]:
            best_overall = (top_score, top_cand, top_detail)
        print(f"gen {gen + 1}/{args.generations}: best {top_detail} "
              f"(evaluated {len(scored)} candidates)", flush=True)

        if top_level > args.level:
            print(f"SOLVED level {args.level} in {len(top_cand)} segments")
            break

    _, cand, detail = best_overall
    print(f"best: {detail}")
    if args.out and cand:
        text, _ = build_script(cand)
        Path(args.out).write_text(text)
        print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
