// Runs the actual (unmodified) blocking SDLPoP game loop inside a dedicated Worker, so
// blocking it doesn't freeze the browser tab -- see "Phase B" in
// docs/plans/13-platform-architecture-unification.md.
//
// Frames and audio reach the main thread via WasmRenderer::render_present/pump_audio ->
// post_frame_to_js/post_audio_to_js (rust/src/platform/wasm.rs), which call this Worker's
// own `postMessage` reflectively -- this script never calls postMessage itself for those, it
// just runs the game.
//
// Input works the other direction and needs a different mechanism: run_game() never returns,
// so this Worker's `onmessage` handler cannot fire once the game is running (a Worker can't
// process incoming messages while a synchronous call still occupies the stack). The one
// message it *can* receive is this file's very first one, sent immediately after the Worker
// is created and before run_game() is ever called -- carrying a SharedArrayBuffer the main
// thread will keep writing live keyboard/mouse state into directly, with no further messages
// needed afterward. See set_shared_input_buffer's doc comment (rust/src/lib.rs) and
// platform::wasm's "Live input" section for the full design.
import init, { preload_file, run_game, resume_game_after_restart, set_shared_input_buffer, init_persistent_storage } from './pkg/sdlpop.js';

// wasm32 has no working non-local-jump/unwind primitive (catch_unwind cannot catch anything
// on this target -- see seg000.rs's start_game doc comment), so a game restart (title screen
// "press any key", death/retry, ...) is signaled by throwing a real JS Error across the
// wasm/JS boundary instead -- the one mechanism that actually works, since it relies on the
// JS engine's own exception propagation, not Rust's. That throw unwinds the *entire* wasm
// call stack, so recovering means calling back into wasm fresh: resume_game_after_restart()
// re-enters directly at the game's restart point, skipping run_game()'s one-time setup
// (which must not re-run). Must match seg000::RESTART_SIGNAL exactly.
const RESTART_SIGNAL = 'SDLPOP_RESTART';
function isRestartSignal(e) {
    return e instanceof Error && e.message === RESTART_SIGNAL;
}

// Runs `first` once, then keeps calling `resume_game_after_restart` every time a restart is
// signaled. A non-restart exception (a real panic/bug) propagates out normally -- this must
// not swallow those, only intentional restarts.
function runWithRestartRetries(first) {
    try {
        first();
        return; // returned normally -- the game loop genuinely ended, no restart happened
    } catch (e) {
        if (!isRestartSignal(e)) throw e;
    }
    while (true) {
        try {
            resume_game_after_restart();
            return; // returned normally -- the game loop genuinely ended, not a restart
        } catch (e) {
            if (!isRestartSignal(e)) throw e;
        }
    }
}

const inputReady = new Promise((resolve) => {
    self.onmessage = (e) => {
        if (e.data.type === 'init') {
            resolve(e.data.sharedInput);
        }
    };
});

// data_manifest.txt is generated by scripts/build_wasm.sh -- every file actually on disk
// under data/, plus SDLPoP.ini -- not the real asset-manifest design from the plan's "asset
// manifest / preload strategy" future consideration (no offline/PWA caching, no lazy
// per-level loading, just "fetch everything up front"). Good enough for a first working
// version; paths are relative to this script's own location (web/), which build_wasm.sh
// symlinks data/ and SDLPoP.ini into, the same way scripts/run_harness.sh does for the
// native binary's working directory.
async function fetchManifest() {
    const res = await fetch('data_manifest.txt');
    if (!res.ok) {
        throw new Error(`failed to fetch data_manifest.txt: ${res.status} ${res.statusText}`);
    }
    return (await res.text()).split('\n').map((l) => l.trim()).filter(Boolean);
}

async function preloadAsset(path) {
    const res = await fetch(path);
    if (!res.ok) {
        throw new Error(`failed to fetch ${path}: ${res.status} ${res.statusText}`);
    }
    preload_file(path, new Uint8Array(await res.arrayBuffer()));
}

async function main() {
    await init();
    const sharedInput = await inputReady;
    set_shared_input_buffer(sharedInput);
    const paths = await fetchManifest();
    // The full asset set is ~4MB/~1000 files (confirmed by `du -sh data/`) -- small enough that
    // whole-game preload-up-front (no lazy per-level loading) is the right call, not a
    // corner cut. What a real preload strategy for a set this size still needs is loading
    // *feedback*: a raw "preloading..." message gives no sense of progress on a slow
    // connection, so report counts as files complete.
    let loaded = 0;
    postMessage({ type: 'status', message: `preloading 0/${paths.length} assets...` });
    // Simple bounded-concurrency fetch pool -- 1000+ simultaneous fetches works but is a
    // needlessly large number of in-flight requests for a local dev server to juggle at once.
    const CONCURRENCY = 24;
    let next = 0;
    async function worker() {
        while (next < paths.length) {
            const path = paths[next++];
            await preloadAsset(path);
            loaded++;
            postMessage({ type: 'status', message: `preloading ${loaded}/${paths.length} assets...`, progress: loaded / paths.length });
        }
    }
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));
    // Loads any existing quicksave/PRINCE.SAV/PRINCE.HOF/SDLPoP.cfg from OPFS into the VFS,
    // and opens the sync access handles fclose()/fflush() write through to for the rest of
    // the session (rust/src/wasm_persist.rs). Must happen before run_game() -- same reason
    // set_shared_input_buffer does: nothing here can run once run_game()'s blocking loop
    // starts.
    await init_persistent_storage();
    postMessage({ type: 'status', message: `preloaded ${paths.length} assets, starting game` });
    runWithRestartRetries(run_game);
}

main().catch((err) => {
    postMessage({ type: 'error', message: String(err && err.stack || err) });
    throw err;
});
