// Runs the actual (unmodified) blocking SDLPoP game loop inside a dedicated Worker, so
// blocking it doesn't freeze the browser tab -- see "Phase B" in
// docs/plans/13-platform-architecture-unification.md.
//
// Frames-out only (explicit sequencing decision: frames first, then input). Every finished
// frame reaches here via WasmRenderer::render_present -> post_frame_to_js
// (rust/src/platform/wasm.rs), which calls the Worker's own `postMessage` reflectively --
// this script never calls postMessage itself for frames, it just runs the game.
//
// Input is NOT wired up yet: run_game() never returns, so this Worker's `onmessage` handler
// (if it had one) could never fire while the game is running -- delivering live input into a
// blocking loop needs SharedArrayBuffer/Atomics, a separate not-yet-started piece.
import init, { preload_file, run_game } from './pkg/sdlpop.js';

// data_manifest.txt is generated by scripts/build_wasm.sh -- every file actually on disk
// under data/, plus SDLPoP.ini -- not the real asset-manifest design from the plan's "asset
// manifest / preload strategy" future consideration (no offline/PWA caching, no lazy
// per-level loading, just "fetch everything up front"). Good enough for a first working
// version; paths are relative to this script's own location (web/), which build_wasm.sh
// symlinks data/ and SDLPoP.ini into, the same way scripts/run_harness.sh does for the
// native binary's working directory.
async function fetchManifest() {
    const res = await fetch('data_manifest.txt');
    if (!res.ok) {
        throw new Error(`failed to fetch data_manifest.txt: ${res.status} ${res.statusText}`);
    }
    return (await res.text()).split('\n').map((l) => l.trim()).filter(Boolean);
}

async function preloadAsset(path) {
    const res = await fetch(path);
    if (!res.ok) {
        throw new Error(`failed to fetch ${path}: ${res.status} ${res.statusText}`);
    }
    preload_file(path, new Uint8Array(await res.arrayBuffer()));
}

async function main() {
    await init();
    const paths = await fetchManifest();
    postMessage({ type: 'status', message: `preloading ${paths.length} assets...` });
    // Simple bounded-concurrency fetch pool -- 1000+ simultaneous fetches works but is a
    // needlessly large number of in-flight requests for a local dev server to juggle at once.
    const CONCURRENCY = 24;
    let next = 0;
    async function worker() {
        while (next < paths.length) {
            const path = paths[next++];
            await preloadAsset(path);
        }
    }
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));
    postMessage({ type: 'status', message: `preloaded ${paths.length} assets, starting game` });
    run_game();
}

main().catch((err) => {
    postMessage({ type: 'error', message: String(err && err.stack || err) });
    throw err;
});
