// Runs the actual (unmodified) blocking SDLPoP game loop inside a dedicated Worker, so
// blocking it doesn't freeze the browser tab -- see "Phase B" in
// docs/plans/13-platform-architecture-unification.md.
//
// Frames and audio reach the main thread via WasmRenderer::render_present/pump_audio ->
// post_frame_to_js/post_audio_to_js (rust/src/platform/wasm.rs), which call this Worker's
// own `postMessage` reflectively -- this script never calls postMessage itself for those, it
// just runs the game.
//
// Input works the other direction and needs a different mechanism: run_game() never returns,
// so this Worker's `onmessage` handler cannot fire once the game is running (a Worker can't
// process incoming messages while a synchronous call still occupies the stack). The one
// message it *can* receive is this file's very first one, sent immediately after the Worker
// is created and before run_game() is ever called -- carrying a SharedArrayBuffer the main
// thread will keep writing live keyboard/mouse state into directly, with no further messages
// needed afterward. See set_shared_input_buffer's doc comment (rust/src/lib.rs) and
// platform::wasm's "Live input" section for the full design.
import init, { preload_file, run_game, set_shared_input_buffer } from './pkg/sdlpop.js';

const inputReady = new Promise((resolve) => {
    self.onmessage = (e) => {
        if (e.data.type === 'init') {
            resolve(e.data.sharedInput);
        }
    };
});

// data_manifest.txt is generated by scripts/build_wasm.sh -- every file actually on disk
// under data/, plus SDLPoP.ini -- not the real asset-manifest design from the plan's "asset
// manifest / preload strategy" future consideration (no offline/PWA caching, no lazy
// per-level loading, just "fetch everything up front"). Good enough for a first working
// version; paths are relative to this script's own location (web/), which build_wasm.sh
// symlinks data/ and SDLPoP.ini into, the same way scripts/run_harness.sh does for the
// native binary's working directory.
async function fetchManifest() {
    const res = await fetch('data_manifest.txt');
    if (!res.ok) {
        throw new Error(`failed to fetch data_manifest.txt: ${res.status} ${res.statusText}`);
    }
    return (await res.text()).split('\n').map((l) => l.trim()).filter(Boolean);
}

async function preloadAsset(path) {
    const res = await fetch(path);
    if (!res.ok) {
        throw new Error(`failed to fetch ${path}: ${res.status} ${res.statusText}`);
    }
    preload_file(path, new Uint8Array(await res.arrayBuffer()));
}

async function main() {
    await init();
    const sharedInput = await inputReady;
    set_shared_input_buffer(sharedInput);
    const paths = await fetchManifest();
    postMessage({ type: 'status', message: `preloading ${paths.length} assets...` });
    // Simple bounded-concurrency fetch pool -- 1000+ simultaneous fetches works but is a
    // needlessly large number of in-flight requests for a local dev server to juggle at once.
    const CONCURRENCY = 24;
    let next = 0;
    async function worker() {
        while (next < paths.length) {
            const path = paths[next++];
            await preloadAsset(path);
        }
    }
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));
    postMessage({ type: 'status', message: `preloaded ${paths.length} assets, starting game` });
    run_game();
}

main().catch((err) => {
    postMessage({ type: 'error', message: String(err && err.stack || err) });
    throw err;
});
